server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      force: true

spring:
#  datasource:
#    url: jdbc:h2:mem:test;MODE=MySQL
#    driver-class-name: org.h2.Driver
#    username: modu
#    password:
  datasource:
    url: jdbc:mysql://localhost:3306/modumenu?useSSL=false&allowPublicKeyRetrieval=true&profileSQL=true&logger=Slf4JLogger&maxQuerySizeToLog=999999&rewriteBatchedStatements=true # MySQL 8.x부터 useSSL=false 추가 필요
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show-sql: true
        format_sql: true
      default_batch_fetch_size: 100 # oneToMany 사용시 in 쿼리 자동으로 작성
    open-in-view: false # OSIV = false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher